name: CraftSlotCommands2
main: com.gmail.bobason01.CraftSlotCommands
version: 1.0
author: Rewritten Aria Sangarin's abandoned plugin
api-version: 1.13
commands:
    craftslotcommands:
        description: Admin command for CraftSlotCommands.
        aliases: [csc]
permissions:
    csc.admin:
        description: Access to the CraftSlotCommands command.
        default: op